### ISSUE TITLE
Sort Alumni by Graduation Year

### ISSUE THREAD

**Issue by euisuny** [plclub/plclub-web#2]
Suggestion from @cdstanford

**Comment by cdstanford** [comment]
Seems like it should be a simple change -- just need to write a Haskell function that sorts the list (alum). But I am not sure I'm familiar enough with how Hakyll and lib/PLClub.hs works to implement this. Also, what is the alumGroup list?

**Comment by euisuny** [comment]
^ @dunnl implemented the Hakyll part, so they definitely know more about this. It looks like the **sortTagsBy** function might help? (https://jaspervdj.be/hakyll/reference/Hakyll-Web-Tags.html)

**Comment by dunnl** [comment]
This is a good idea but I'll have to think about it. The list of alumni is basically a set of pointers that don't get resolved until the template of *index.html* is instantiated, which is handled by Hakyll itself.

**Comment by dunnl** [comment]
Merged
